config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :flats, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :address, :price_per_night, :number_of_guests, presence: true
  validates :price_per_night, :number_of_guests, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<nav class="navbar navbar-light bg-light border-bottom">
  <div class="container-fluid">
  <div class="navbar-brand"><i class="fa-solid fa-house-user"></i> <%= link_to "Flats", flats_path %></div>
    <form class="d-flex">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
</nav>

<div class="container p-4 m-4">
  <h1>All our flats (<%= @flats.count %>)</h1>
  <div class="flats row align-items-start">
    <% @flats.each do |flat| %>
    <div class="flat card col m-3 p-3 rounded bg-secondary bg-gradient" id="flat<%= flat.id%>">
      <h3 class="text-light text-center"><%= flat.name %></h3>
      <p class="m-0"><%= flat.address %></p>
      <img src="<%= flat.img_url %>" class="rounded-3 my-3" alt="">
      <h4 class="text-light">Description:</h4>
      <p class="text-light"><%= flat.description %></p>
      <div class="d-flex justify-content-between p-2">
        <p class="text-info"><i class="fa-solid fa-euro-sign"></i> <%= flat.price_per_night %></p>
        <p class="text-warning"><i class="fa-solid fa-people-roof"></i> <%= flat.number_of_guests %></p>
      </div>
      <p class="py-2 m-0 border-top text-light"><%= link_to "More info", flat_path(flat) %></p>
    </div>
    <% end %>
  </div>
</div>

app/views/flats/show.html.erb
<nav class="navbar navbar-light bg-light border-bottom">
  <div class="container-fluid">
  <div class="navbar-brand"><i class="fa-solid fa-house-user"></i> <%= link_to "Flats", flats_path %></div>
    <form class="d-flex">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>